config/routes.rb
Rails.application.routes.draw do
  root 'writers#index'

  resources :writers do
    resources :books, shallow: true
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :writer
  validates :title, presence: true
end

app/models/writer.rb
class Writer < ActiveRecord::Base
  validates :name, length: {in: 2..20}, presence: true
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # shallow instance variables
# @book = Book.find params[:id]
# @writer = @book.writer

  def index
    @writer = Writer.find params[:writer_id]
    @books = @writer.books
  end

  def new
    @writer = Writer.find params[:writer_id]
    @book = Book.new
  end

  def create
    @writer = Writer.find params[:writer_id]
    @book = Book.new book_params
    @book.writer = @writer
    if @book.save
      redirect_to writer_books_path(@writer)
    else
      render :new
    end
  end

  def show
    @book = Book.find params [:id]
    @writer = @book.writer
  end

  def update
    @book = Book.find params[:id]
    @book.update_attributes book_params
    @author = @book.author
    if @book.save
      redirect_to book_path(@book)
    else
      render :edit
    end

  end

  def edit
    @book = Book.find params [:id]
    @writer = @book.writer
  end

  def destroy
    book = Book.find params[:id]
    book.destroy
    redirect_to writer_books_path(book.writer)
  end

  private
  def book_params
    params.require(:book).permit(:title, :writer_id)
  end
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController

# shallow instacen variables
# @book = Book.find params[:id]
# @author = @book.author


  def index
    @writer = Writer.all
  end

  def show
    @writer = Writer.find params[:id]
  end

  def new
    @writer = Writer.new
  end

  def create 
    @writer = Writer.new writer_params
    if @writer.save
      redirect_to writers_path
    else
      render :new
    end
  end

  def edit
    @writer = Writer.find params[:id]
  end

  def update 
    @writer = Writer.find params[:id]
    if @writer.update_attributes writer_params
      redirect_to writer_path(@writer)
    else
      render :edit
    end
  end

  def destroy
    writer = Writer.find params[:id]
    writer.destroy
    redirect_to writers_path
  end
  private
  def writer_params
    params.require(:writer).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Author</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/writers/edit.html.erb
<h2>Edit this puppy!</h2>
<% if @writer.errors.any?%>
  <% @writer.errors.full_messages.each do |error|%>
    <p class="text-danger">
      <%= error %>
    </p>
  <% end%>
<% end %>

<%= form_for @writer do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
</p>
<%= link_to "Delete this writer?", author_path, method:"Delete", data:{ confirm: "Are you sure you want to delete #{@writer.name}?"} %>
<p>
<%= link_to "Back to Home", writers_path%>
</p>
<% end %>

app/views/writers/index.html.erb
<h1>Thy Writers.</h1>

<% @writer.each do |writer| %>
<p>
<%= link_to writer.name, writer_path(writer)%>
</p>

<% end %>
<%= link_to "Add a writer!", new_writer_path %>

app/views/writers/new.html.erb
<h2>Add a new Writer!</h2>
<% if @writer.errors.any?%>
  <% @writer.errors.full_messages.each do |error|%>
    <p class="text-danger">
      <%= error %>
    </p>
  <% end%>
<% end %>

<%= form_for @writer do |f| %>
<p>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
</p>
<p>
<%= link_to "Back to Home", writers_path%>
</p>
<% end %>

app/views/writers/show.html.erb
<h2><%= @writer.name %></h2>
<%= link_to "Edit this writer", edit_writer_path(@writer) %>
<p>
<%= link_to "Back to Home", writers_path%>
</p>